### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by MaxWasUnavailable** [AverageAnime/create-metalwork#18]
```
[21Aug2024 22:56:24.136] [Render thread/ERROR] [mezz.jei.library.util.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Create: Metalwork createmetalwork:create/compat/mixing/ingot_melting/molten_netherite_from_melting class com.simibubi.create.content.kinetics.mixer.MixingRecipe

java.lang.IllegalStateException: Can't modify the empty stack.
	at net.minecraftforge.fluids.FluidStack.setAmount(FluidStack.java:175) ~[forge-1.20.1-47.3.7-universal.jar%231051!/:?]
	at com.simibubi.create.compat.jei.category.CreateRecipeCategory.withImprovedVisibility(CreateRecipeCategory.java:129) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.category.BasinCategory.setRecipe(BasinCategory.java:96) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.category.BasinCategory.setRecipe(BasinCategory.java:33) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:141) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:114) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at com.simibubi.create.compat.jei.category.CreateRecipeCategory.registerRecipes(CreateRecipeCategory.java:82) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.CreateJEI.lambda$registerRecipes$23(CreateJEI.java:340) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.simibubi.create.compat.jei.CreateJEI.registerRecipes(CreateJEI.java:340) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$11(PluginLoader.java:147) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:147) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:130) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:130) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:98) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[21Aug2024 22:56:24.142] [Render thread/ERROR] [mezz.jei.library.util.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Create: Metalwork createmetalwork:create/compat/mixing/ingot_melting/molten_lead_from_melting_oreganized class com.simibubi.create.content.kinetics.mixer.MixingRecipe

java.lang.IllegalStateException: Can't modify the empty stack.
	at net.minecraftforge.fluids.FluidStack.setAmount(FluidStack.java:175) ~[forge-1.20.1-47.3.7-universal.jar%231051!/:?]
	at com.simibubi.create.compat.jei.category.CreateRecipeCategory.withImprovedVisibility(CreateRecipeCategory.java:129) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.category.BasinCategory.setRecipe(BasinCategory.java:96) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.category.BasinCategory.setRecipe(BasinCategory.java:33) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:141) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:114) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at com.simibubi.create.compat.jei.category.CreateRecipeCategory.registerRecipes(CreateRecipeCategory.java:82) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at com.simibubi.create.compat.jei.CreateJEI.lambda$registerRecipes$23(CreateJEI.java:340) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.simibubi.create.compat.jei.CreateJEI.registerRecipes(CreateJEI.java:340) ~[create-1.20.1-0.5.1.f.jar%23704!/:0.5.1.f]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$11(PluginLoader.java:147) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:147) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:130) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:130) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:98) ~[jei-1.20.1-forge-15.12.3.55.jar%23824!/:15.12.3.55]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231046!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

**Comment by AverageAnime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issues](https://trello.com/c/NLFH4q6x/17-github-issues)
